module Recall
  # Machine-local configuration. Users edit config/recall.rb and
  # config/recall.local.rb via the DSL exposed in `Recall.configure` —
  # do not edit this file. See config/recall.rb for AI-facing instructions.
  module Config
    class << self
      attr_accessor :claude_code_dirs, :codex_dir, :opencode_db,
                    :domain_rules, :default_domain,
                    :ollama_host, :ollama_default_model,
                    :claude_code_default_model, :opencode_default_model, :codex_default_model,
                    :claude_code_work_dir_prefix, :claude_code_work_config_dir,
                    :data_dir

      def configure
        yield DSL.new(self)
      end

      def reset!
        @claude_code_dirs            = []
        @codex_dir                   = nil
        @opencode_db                 = nil
        @domain_rules                = []
        @default_domain              = "personal"
        @ollama_host                 = "http://localhost:11434"
        @ollama_default_model        = "qwen2.5:14b"
        @claude_code_default_model   = "claude-sonnet-4-20250514"
        @opencode_default_model      = "kimi-k2.5"
        @codex_default_model         = "codex"
        @claude_code_work_dir_prefix = nil
        @claude_code_work_config_dir = nil
        @data_dir                    = ENV["RECALL_DATA_DIR"] || File.join(Dir.home, ".config", "recall")
      end

      def domains
        (Array(domain_rules).map { |r| r[:domain] } + [ default_domain ]).uniq.compact
      end

      def domain_for_path(path)
        return default_domain if path.blank?
        rule = Array(domain_rules).find { |r| path.to_s.match?(r[:match]) }
        rule ? rule[:domain] : default_domain
      end

      def claude_code_work_dir_prefix_expanded
        claude_code_work_dir_prefix && File.expand_path(claude_code_work_dir_prefix)
      end

      def claude_code_work_config_dir_expanded
        claude_code_work_config_dir && File.expand_path(claude_code_work_config_dir)
      end
    end

    # DSL yielded by Recall.configure. List-type settings (sources, domain
    # rules) accumulate across configure blocks; scalars (ollama_host, etc.)
    # are set with plain `=` and fall through to Config via method_missing.
    class DSL
      def initialize(target)
        @target = target
      end

      def claude_code(path, as:)
        @target.claude_code_dirs << { path: path, name: as }
      end

      def codex(path)
        @target.codex_dir = path
      end

      def opencode(path)
        @target.opencode_db = path
      end

      def domain(name, matching:)
        @target.domain_rules << { match: matching, domain: name }
      end

      def claude_code_work_profile(prefix:, config_dir:)
        @target.claude_code_work_dir_prefix = prefix
        @target.claude_code_work_config_dir = config_dir
      end

      def respond_to_missing?(name, include_private = false)
        @target.respond_to?(name, include_private) || super
      end

      def method_missing(name, *args, **kwargs, &block)
        if @target.respond_to?(name)
          @target.public_send(name, *args, **kwargs, &block)
        else
          super
        end
      end
    end

    reset!
  end

  def self.configure(&block)
    Config.configure(&block)
  end
end
